### ISSUE TITLE
API search: Filtering by human-only diseases

### ISSUE THREAD

**Issue by aalmazan** [monarch-initiative/helpdesk#126]
Hello! Hopefully this does not belong on the MONDO repo as I think it's more API related.

I am looking to use the API specifically for looking for human diseases, however, I'll get non-human results.

For example, searching for `alpha-mannosidosis` will show results:

*  `alpha-mannosidosis`
* `alpha-mannosidosis, non-human animal`
* `alpha-mannosidosis, cattle`
* etc

On the detail pages for the non-human entries (i.e. https://monarchinitiative.org/MONDO:1010172) there is a section for hierarchy. I believe that could be enough on my end to use to filter out non-human entries, but this doesn't exist on search results.

Please let me know if there's something that already exists, or a suggested way forward.

Thanks!

**Comment by kevinschaper** [comment]
Hi @aalmazan,

I think a very similar question came up in another issue. We're not set up to return the collection of all descendants from Monarch API, but [this answer](https://github.com/monarch-initiative/monarch-app/issues/667#issuecomment-2030881597) links to a pretty easy method of doing it via Oaklib  and the same solution would apply. Assuming you're looking for a list of all descendants of human disease, this would be the command (after installing oaklib): 

```
runoak -i sqlite:obo:mondo descendants MONDO:070009 -p i
```

**Comment by aalmazan** [comment]
Hi @kevinschaper thanks for replying. That does indeed look promising. 

For those with the same question as this thread, I'll be using `runoak` to look for any entry that has `non-human animal` ancestors and filtering accordingly. Example below.

![image](https://github.com/monarch-initiative/helpdesk/assets/800948/34be0d86-26d5-4fca-ae6a-2e8aebfb9841)

**Comment by aalmazan** [comment]
Closing as relatively solved from feedback, though a hierarchical filter on search would still be appreciated :) .
