### ISSUE TITLE
Ortholog Phenotype selection on Beta site

### ISSUE THREAD

**Issue by stephditroia** [monarch-initiative/helpdesk#13]
Please add back the ability to select or de-select organisms in the ortholog phenotype section. Thanks!

**Comment by monicacecilia** [comment]
Hello @stephditroia, 

Thanks for sharing this feedback. We are delighted to see our users testing the BETA site for the Monarch Initiative. 

You are still able to filter the information in the ortholog tab by using the 'Taxon Filter' button at the top of the list of orthologs. Be sure to make your selection, then click on the 'Apply & Close' button to reveal the filtered information. As you navigate to other tabs in the page, the filter will be reset. 

This button is also available on the 'homolog' and 'variant' tables. 

Please give it a try. And  please feel free to contact us again, should you need any assistance. 

<img width="1122" alt="Screen Shot 2020-02-05 at 3 50 56 PM" src="https://user-images.githubusercontent.com/1714621/73893741-57af7200-482f-11ea-977c-9bfeb7db1d07.png">
