### ISSUE TITLE
Discrepancies between TSV and Monarch-KG Data

### ISSUE THREAD

**Issue by nickzren** [monarch-initiative/helpdesk#131]
I have downloaded data from Monarch Initiative (https://data.monarchinitiative.org/), specifically from the following sub sources:
- TSV: [TSV Data](https://data.monarchinitiative.org/latest/tsv/)
- Monarch-KG: [Monarch-KG Data](https://data.monarchinitiative.org/monarch-kg/latest/)

### Observations:
- **Assumption:** Data from both sources should be quite similar as the TSV was the resource for the original Monarch Initiative site, while the new site is based on Monarch-KG data.
- **Discrepancies:** 
  - **Gene-Disease Associations:**
  
Example records present in TSV but not in Monarch-KG:
| subject   | subject_label | subject_taxon | subject_taxon_label | object       | object_label            | relation  | relation_label         | evidence             | evidence_label                                                            | source                                                                                     | is_defined_bqualifier |
|-----------|---------------|---------------|---------------------|--------------|-------------------------|-----------|------------------------|----------------------|---------------------------------------------------------------------------|-------------------------------------------------------------------------------------------|------------------------|
| HGNC:10004 | RGS9          | NCBITaxon:9606 | Homo sapiens        | MONDO:0012033 | bradyopsia              | RO:0003303 | causes condition       | ECO:0000322|ECO:0000220 | imported manually asserted information used in automatic assertion|sequencing assay evidence | https://archive.monarchinitiative.org/#omim|https://archive.monarchinitiative.org/#orphanet | direct                 |
| HGNC:10008 | RHCE          | NCBITaxon:9606 | Homo sapiens        | MONDO:0019107 | Rh deficiency syndrome  | RO:0004013 | is causal germline mutation in | ECO:0000322         | imported manually asserted information used in automatic assertion                       | https://archive.monarchinitiative.org/#orphanet                                             | direct                 |

Example records present in Monarch-KG but not in TSV:
| subject   | subject_label | subject_category | subject_taxon | subject_taxon_label | negated | predicate      | object       | object_label                                  | object_category  | qualifiers | publications | has_evidence | primary_knowledge_source | aggregator_knowledge_source                | object_taxon | object_taxon_label | object_taxon:1 | object_taxon_label:1 |
|-----------|---------------|------------------|---------------|---------------------|---------|----------------|--------------|-----------------------------------------------|------------------|------------|--------------|--------------|--------------------------|--------------------------------------------|--------------|--------------------|----------------|------------------------|
| HGNC:10001 | RGS5          | biolink:Gene     | NCBITaxon:9606 | Homo sapiens        |         | biolink:causes | MONDO:0007781 | essential hypertension, genetic               | biolink:Disease  |            |              | infores:omim | infores:monarchinitiative|infores:medgen                              |              |                    |                |                        |
| HGNC:10004 | RGS9          | biolink:Gene     | NCBITaxon:9606 | Homo sapiens        |         | biolink:causes | MONDO:0958180 | prolonged electroretinal response suppression 1 | biolink:Disease  |            |              | infores:omim | infores:monarchinitiative|infores:medgen                              |              |                    |                |                        |

  - **Gene-Phenotype Associations:**
    - TSV data can have phenotype identifiers from MONDO, EFO, or HPO.
    - Monarch-KG data only has HPO IDs.

### Request:
Could you please provide clarification on why these discrepancies exist between the TSV and Monarch-KG data? Assuming the data from Monarch-KG is more accurate.?

**Comment by kevinschaper** [comment]
Hi @nickzren,

The tsv files for the new KG build are here: https://data.monarchinitiative.org/monarch-kg/latest/tsv/index.html

I've been a little hesitant to move artifacts from the old build, which were put at the root of data.monarchinitiative.org out of concern for breaking anyone's pipelines, but the confusion that you ran into is exactly why I should move them. 

data.monarchinitiative.org/latest & data.monarchinitiative.org/YYYYMM are the directories from the old build that we should move down/aside to reduce confusion, data.monarchinitiative.org/monarch-kg/latest is the release from the new pipeline - and _hopefully_ the tsv files from within a new release will match the full kg tsv!   (plus or minus columns, download files for specific categories should only have relevant columns for that association category)

**Comment by nickzren** [comment]
Ok, I see. So if I need to use the data from now on, it should always rely on data from data.monarchinitiative.org/monarch-kg/latest since it’s from the new pipeline, rather than data from data.monarchinitiative.org/latest which is from the old pipeline. Correct?

**Comment by nickzren** [comment]
Very helpful, thanks a lot @kevinschaper !

**Comment by nickzren** [comment]
Quick question: In the old data pipeline that generated gene-phenotype data, there was a field named valid_monogenic_record. However, I don’t see this field in the data generated by the new pipeline. How can we retrieve records where valid_monogenic_record is True for monogenic genes and phenotypes? Thank you

**Comment by kevinschaper** [comment]
Oh, good question! `primary_knowledge_source` is the roughly equivalent field in the new model. It identifies the original provider of the data, and those `infores` identifiers are fully defined here: https://github.com/biolink/information-resource-registry/blob/main/infores_catalog.yaml

`aggregator_knowledge_source` has a bit of tracking, it always includes infores:monarchinitiative as the most recent source, but may also show an intermediate aggregator, if we didn't get the edge from the original source.

**Comment by nickzren** [comment]
It seems the `is_defined_by` field in the old data had the following categories:
1. https://data.monarchinitiative.org/ttl/clinvar.nt
2. https://archive.monarchinitiative.org/#hpoa
3. https://archive.monarchinitiative.org/#omim
4. https://archive.monarchinitiative.org/#orphanet
5. https://archive.monarchinitiative.org/#coriell
6. https://archive.monarchinitiative.org/#gwascatalog

Now, `primary_knowledge_source` only shows `infores:hpo-annotations` and `{infores:monarchinitiative}` for `aggregator_knowledge_source`.

That’s fine, I was just clarifying the difference.

Quick question: Monarch KG has 6,675 unique gene-disease pairs, while HPO Annotations ([genes_to_disease](https://purl.obolibrary.org/obo/hp/hpoa/genes_to_disease.txt)) has 15k, with 6,727 related to MENDELIAN diseases based on `association_type`. Is Monarch KG intentionally filtering down to MENDELIAN diseases only?

Thank you

**Comment by kevinschaper** [comment]
We've been working to ensure a common gene to disease association set across all of Monarch, coming in via the HPOA pipeline. I think primary vs aggregator is a little grey on this, since I'm guessing the knowledge originates with OMIM or Orphanet. 

We're splitting the causal/MENDELIAN and non-causal (POLYGENIC/UNKNOWN) into different files, the non-causal g2d associations are here: https://data.monarchinitiative.org/monarch-kg/latest/tsv/gene_associations/gene_disease.noncausal.tsv.gz
