### ISSUE TITLE
Get heritability (inheritance) through web services

### ISSUE THREAD

**Issue by praveenraj2018** [monarch-initiative/helpdesk#16]
hello monarch support team,

I am wondering is there a way to get the heritability (inheritance) of the mondo disease? Which web service API would provide the information? Request your support.

Thanks
Raj

**Comment by monicacecilia** [comment]
Hi Raj, 
I'm pinging @nicolevasilevsky and @kshefchek, who may be able to offer some insight. Thanks!

**Comment by kshefchek** [comment]
yes, you can use the https://api.monarchinitiative.org/api/bioentity/disease/{id} endpoint to fetch information about heritability, for example:

https://api.monarchinitiative.org/api/bioentity/disease/MONDO:0007947

Note that there's some duplication (this likely comes from merging Orphanet and OMIM ids from HPO), so you may want to uniquify the results on your side.

**Comment by praveenraj2018** [comment]
Thank you Kent. I will check as you suggested and get back .

Thanks for the prompt response.

Praveen

**Comment by andreabertana** [comment]
Hi @kshefchek and @monicacecilia ,
Is this still the only way to get inheritance? or can it be downloaded now? couldn't find it in tsv files [here](https://data.monarchinitiative.org/latest/index.html) nor in https://github.com/monarch-initiative/mondo/releases/tag/v2022-06-01. 
Thanks
Andrea
