### ISSUE TITLE
Is there a way to include drug screens that have been done in model organisms

### ISSUE THREAD

**Issue by dnahotline** [monarch-initiative/helpdesk#2]
Some drug screens have been performed in model orgs like mice, zebrafish, fly etc. Are these integrated in Monarch? If not could they be? Would be useful for analyses in Translator or could be for certain other users.

**Comment by nlharris** [comment]
@kshefchek any comment on this?

**Comment by nlharris** [comment]
or @putmantime ?

**Comment by kshefchek** [comment]
I think we ended up discussing this in person during the Spring 2019 hackathon, but I'm not sure if there any updates.  @kevinschaper @sabrinatoro @sierra-moxon do you know of any non-human dbs that have this information?

**Comment by sabrinatoro** [comment]
Databases have their own rules when it comes to curating drug screens. The main issues (I think) are that (1) the amount of work to curate this information is very high, and it is not often "worth" the time in comparison to other information to curate, (2) many of the drugs are not in Chebi (or other local vocabularies) and this makes the whole process very slow.
At ZFIN, we would either not curate drug screen results at all, or we would curate only the drugs which have been shown to improve a phenotype. 
Therefore the data that exist in non-human databases is not complete, and it is rarely reported as "this comes from a drug screen". 
BUT, there is information about how drugs (or chemical) affect phenotypes/diseases (and every database record this information in a different way), and that data is very useful. So it would be nice if we could include it.

**Comment by kshefchek** [comment]
This is super useful! Perhaps the next step would be to spec out a plan to get drug/chemical to phenotype/disease associations for each data source.  We should probably close here and relocate to monarch-ingest.
