### ISSUE TITLE
question about https://monarchinitiative.org/disease/MONDO:0005010#phenotype

### ISSUE THREAD

**Issue by msincan** [monarch-initiative/helpdesk#21]
**Please describe your question, suggestion, or concern.**
I am having trouble understanding why "hydatidiform mole, recurrent, 2" is listed on this page. I was expecting only to see a list of phenotypes associated with MONDO5010- Coronary Artery Disease. 
Thanks.

**Comment by kshefchek** [comment]
thanks for reporting this! I have created a ticket in mondo to fix this - https://github.com/monarch-initiative/mondo/issues/1593
