### ISSUE TITLE
How do I download the results of a search in Monarch?

### ISSUE THREAD

**Issue by nursatranscriptomine** [monarch-initiative/helpdesk#22]
I ran a search for a disease in Monarch and pulled up a list of genes, but don't see any way to download them for a downstream analysis - can you assist?

**Comment by kshefchek** [comment]
We're currently working on adding this feature to our app, the ticket to track this is here - https://github.com/monarch-initiative/monarch-ui/issues/278

In the meantime there are some workarounds, you can use our [API](https://api.monarchinitiative.org/api/) to perform a disease-gene lookup, for example:
https://api.monarchinitiative.org/api/bioentity/disease/MONDO:0010011/genes?rows=100&association_type=both

You can also prefix any URL with legacy to get tables with a TSV option, for example
https://legacy.monarchinitiative.org/disease/MONDO:0010011#gene-causal

**Comment by nursatranscriptomine** [comment]
Thanks....appreciated
