### ISSUE TITLE
Download RDF human gene-gene interaction

### ISSUE THREAD

**Issue by AlejandroTL** [monarch-initiative/helpdesk#30]
Hello!

First of all: super cool and interesting initiative, really nice!

Now the question: I would like to download the RDF files of the human gene-gene interaction Knowledge Graph, but I cannot find it on Downloads, how can I access to it? Is there some kind of SPARQL endpoint to make queries or is it mandatory to use the BioLink API to access to the data?

Thank you so much!

**Comment by nlharris** [comment]
Hi @AlejandroTL, thanks for your question and sorry for the slow response! @kshefchek is this something you could answer?

**Comment by kshefchek** [comment]
@AlejandroTL you can download our rdf here:
https://archive.monarchinitiative.org/latest/rdf/

For interactions you would want
https://archive.monarchinitiative.org/latest/rdf/biogrid.ttl
https://archive.monarchinitiative.org/latest/rdf/string.ttl

however note that this does not get you id normalization, which we only offer as a tsv format here:
https://archive.monarchinitiative.org/latest/tsv/all_associations/gene_interaction.all.tsv.gz
