### ISSUE TITLE
Question about a specific Mondo mapping choice ("Hereditary Hemochromatosis")

### ISSUE THREAD

**Issue by Sean-Ontoforce** [monarch-initiative/helpdesk#31]
Hey there,

I've been getting into the Mondo Ontology lately and I'm loving it so far.
Just had a small question just for clarification.
The term "Hereditary Hemochromatosis" (http://purl.obolibrary.org/obo/MONDO_0006507) in Mondo is mapped to the "Haemochromatosis" concept in SNOMED (http://identifiers.org/snomedct/399187006), 
but SNOMED does seem to have a "Hereditary haemochromatosis" concept specifically (http://identifiers.org/snomedct/35400008).
Is there any reason as to why it's mapped to the general concept and not the hereditary-specific one?

Thanks in advance!

**Comment by nlharris** [comment]
Thanks for the question, Sean! @nicolevasilevsky is this something you could respond to?

**Comment by nicolevasilevsky** [comment]
Hi @Sean-Ontoforce - thanks for reporting this, we can fix this in Mondo. I'm glad you like working with the Mondo ontology so far! 

For future issues or requests with Mondo, could you please report them here: https://github.com/monarch-initiative/mondo/issues

Thank you!
Nicole

**Comment by nlharris** [comment]
Sounds like this was fixed via that Mondo ticket.
