### ISSUE TITLE
Pre-computed phenotype profile similarities

### ISSUE THREAD

**Issue by eric-czech** [monarch-initiative/helpdesk#34]
Hi, 

Have you ever released pre-computed similarity matrices from the [phenotype analyzer](https://monarchinitiative.org/analyze/phenotypes) when the profiles are seeded based on genes or diseases?  I.e. I'm looking for an N disease x N disease matrix with all the current API results available at https://api.monarchinitiative.org/api/sim/search for a single request.

I would like to do this in bulk without the API if possible and thought I'd ask for suggestions.

Thank you!

**Comment by nlharris** [comment]
Hi @eric-czech, thanks for submitting this question. Hopefully @putmantime or @kshefchek can help you.

**Comment by kshefchek** [comment]
I have generated disease x disease distance matrices in the past, but we have not considered making them a part of our data releases.  There are a number of ways to define distance between diseases, in both the distance metric and how the annotations are selected (if using an annotation based method).  We've also created pipelines to generate graph embeddings of our ontologies, and presumably this could also be used to generate a distance matrix - @justaddcoffee is leading that effort.  @eric-czech if you have an idea of what you would like for your analysis we could point you in the right direction.

**Comment by eric-czech** [comment]
Thanks @kshefchek!  The phenodigm distance metric and HPO terms chosen based on diseases would be great (if that's what you mean by annotations).  Graph embeddings for diseases would also be great -- are those somewhere public?

**Comment by kshefchek** [comment]
@eric-czech it might be easier to discuss over a quick call, could you reach out to me via kent@tislab.org ?

**Comment by nlharris** [comment]
@eric-czech did you get what you needed from Kent? Can we close this ticket?

**Comment by eric-czech** [comment]
Yep, all set!  @kshefchek gave us an intro to @pnrobinson, who we spoke to today.  We haven't figured out anything yet but we're working on it, so there's no need for this issue anymore.
