### ISSUE TITLE
neurodevelopmental disorder MONDO:0700092, gene associations

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/helpdesk#51]
# If your bug report is about Mondo, please file a ticket here instead: https://github.com/monarch-initiative/mondo/issues

## Describe the problem with the Monarch website or APIs

I'm wondering why I see no genes associated with this term in Monarch?
neurodevelopmental disorder MONDO:0700092

A clear and concise description of what the issue is.

## To reproduce

Please include any information you can about what, where, when, and why this happened. Please include any URLs involved in the issue.

## Screenshots

If applicable, add screenshots to help illustrate the problem.

## Additional context

Add any other context about the issue that you feel may be important. e.g. browser version, time of day.

**Comment by kshefchek** [comment]
This is a newly introduced class in Mondo 2021-10-01 and does not have any direct annotations, or any subclasses in which we could infer indirect annotations.  It looks like it has been fully incorporated in the 2021-11-01 version so this page should get some indirect annotations in the next data load.  Please reopen if this sounds incorrect!

**Comment by ValWood** [comment]
I don't understand this. We already have it in PomBase with many children?
https://www.pombase.org/term/MONDO:0700092
Heve these been removed recently?

**Comment by kshefchek** [comment]
Which version is PomBase using?  I'm looking at the files here https://github.com/monarch-initiative/mondo/releases/tag/v2021-10-01 and it looks like it's a new term without subclasses in this version.

**Comment by ValWood** [comment]
mondo: releases/2021-11-01/reasoned.owl.owl

**Comment by ValWood** [comment]
Which version is Monarch using?

**Comment by kshefchek** [comment]
We're using the October release currently

**Comment by ValWood** [comment]
Ah OK, maybe the next update will be OK.  Do you know when that will be? I am looking for  disease gene use cases for a workflow.

**Comment by kshefchek** [comment]
I don't think we'll get another release out in the near term but defer to @putmantime 

in the meantime is there another disease class that could serve as a proxy? perhaps https://monarchinitiative.org/disease/MONDO:0100038 ?

**Comment by ValWood** [comment]
That term does not work so well it's a smaller gene set  for fission yeast orthologs and loses the microtubule-associated subset I am filtering down to. I know the set of genes associated with the term in fission yeast, and I am trying to see how much larger the total human set is.
No hurry, this isn't urgent because I can probably check this in other ways by locating the current children in the ontology and summing the associations to get an approximation.

I do have another question though. Is there a way to download the set of causal genes for (associations to) a MONDO disease term from Monarch? I could not see how to do this.
