### ISSUE TITLE
Legacy site 503 error

### ISSUE THREAD

**Issue by nursatranscriptomine** [monarch-initiative/helpdesk#52]
# If your bug report is about Mondo, please file a ticket here instead: https://github.com/monarch-initiative/mondo/issues

## Describe the problem with the Monarch website or APIs

As suggested in response to a previous ticket, I have been using legacy.monarchinitiative.org to download gene lists since this feature is not available on monarchinitiative.org. However the legacy site is now throwing a 503 error.

## Expected behavior

Legacy site should be working?

## To reproduce

https://legacy.monarchinitiative.org/ ws the page I tried to access.

**Comment by kevinschaper** [comment]
Hi @nursatranscriptomine

Sorry for the down time, the legacy site got a bit lost in the shuffle during a server move and we're working to bring it back.

**Comment by monicacecilia** [comment]
Assuming this issue has been resolved by now. 
@nursatranscriptomine please let us know if you encounter any other challenges.
