### ISSUE TITLE
Data downloads page down

### ISSUE THREAD

**Issue by thuynnguyen** [monarch-initiative/helpdesk#53]
# If your bug report is about Mondo, please file a ticket here instead: https://github.com/monarch-initiative/mondo/issues

## Describe the problem with the Monarch website or APIs

I received a 404 Not Found error when clicking the link to download Monarch data. This happened on 2/15/22 at approximately 4:00PM CST 

## Expected behavior

I expected to be able to download the Monarch database.

## To reproduce

This is the URL I clicked on: https://archive.monarchinitiative.org/latest/

**Comment by kevinschaper** [comment]
Hi @thuynnguyen,

Sorry for the url shake-up. If you look in https://archive.monarchinitiative.org/monarch/latest/ do you see the files/structure that you're looking for?

**Comment by kevinschaper** [comment]
We restored https://archive.monarchinitiative.org/latest/ and I think it should have the same structure that it did before. Are you able to confirm that it's working for you now @thuynnguyen?

**Comment by monicacecilia** [comment]
I'm going to assume this issue has been resolved. 
@thuynnguyen, please re-open and let us know if you come across any other challenges.
