### ISSUE TITLE
no more exomiser data available for download

### ISSUE THREAD

**Issue by lgmgeo** [monarch-initiative/helpdesk#54]
Dear developpers,

I need your help regarding on the download of exomiser data previously available at :
https://data.monarchinitiative.org/exomiser/data/
e.g.: "2019_phenotype.zip"

These data are used during the [AnnotSV](https://github.com/lgmgeo/AnnotSV) installation.

There is no more data available on this site (it seems that a beta version is present):
![image](https://user-images.githubusercontent.com/49909073/157706698-b30c80d2-af83-48f7-b083-c4a73a8ef287.png)

Can you help me and tell me where to download these data?

Many thanks in advance,

Véronique

**Comment by monicacecilia** [comment]
With sincerest apologies Geoffroy (@lgmgeo), we are currently doing some refactoring of our cloud platform configuration and the had to bring our file servers down yesterday for an unplanned outage. We will reach out again ASAP to share the latest update. Please forgive us for the hiccup.

**Comment by lgmgeo** [comment]
No problem at all, I understand.
Thank you for your quick answer!
