### ISSUE TITLE
the scigraph.tgz can't be downloaded

### ISSUE THREAD

**Issue by lyzcool** [monarch-initiative/helpdesk#55]
Hello,the data : 'scigraph.tgz' can't be downloaded, can you give me a share? Thank you!

**Comment by monicacecilia** [comment]
Hi @lyzcool - you should now be able to download ```scigraph.tgz```. Please accept our apologies for any inconvenience this may have caused. And please do not hesitate to reach out to us if you need any additional help.

**Comment by lyzcool** [comment]
I'm so sorry,I can't see it on https://archive.monarchinitiative.org/latest/ ,can you tell me where you upload it,thank you!
