### ISSUE TITLE
SMARCC2 HGNC:11105

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/helpdesk#62]
**Please describe your question, suggestion, or concern.**

SMARCC2 HGNC:11105

Is causal for Coffin-Siris syndrome 8
but "contributes to" for the parent  term "Coffin-Siris syndrome"
which seems odd?

**Comment by nicolevasilevsky** [comment]
Hi @ValWood I'm not sure what the question is - could you please provide some more details? Thanks!

**Comment by ValWood** [comment]
I was wondering whay a gene products is "causal" for a condition but only "contributes_to" for the  parent grouping term:

<img width="1275" alt="Screenshot 2022-06-13 at 17 55 51" src="https://user-images.githubusercontent.com/7359272/173405698-d302f493-4e07-46df-a3f2-08a1a6203255.png">

I ask because we usually only curate single gene causative connections.

**Comment by kevinschaper** [comment]
Hi @ValWood, sorry for letting this sit for so long.

We're in a little bit of an awkward in between position between software stacks. I wasn't able to determine within the older system why that extra annotation is there, but I was able to confirm that it won't be there when we are eventually able to run the website from our new graph.
