### ISSUE TITLE
Typo in gene description text

### ISSUE THREAD

**Issue by PabloBotas** [monarch-initiative/helpdesk#67]
**Mondo term (ID Label)**
https://monarchinitiative.org/gene/HGNC:2151

**Bug/Typo/Error description**
The is a simple typo repeating "cause of" in the description of the gene. Specifically in this line: Defects in this gene are a cause of cause of retinitis pigmentosa type 45.

Not sure if this is on your responsibility or you are taking this from somebody else.

**Your nano-attribution (ORCID)**
https://orcid.org/my-orcid?orcid=0000-0001-7090-9648

**Comment by putmantime** [comment]
I see the new issue in the monarch helpdesk @PabloBotas.
Thank you very much, we are looking into it now.

**Comment by monicacecilia** [comment]
Thank you for sharing this information, @PabloBotas. I have transferred this issue to the Monarch Helpdesk and we will get back with you. 
For future reference, this repository (https://github.com/monarch-initiative/helpdesk/issues) is the appropriate place to report these bugs. Thank you!

**Comment by putmantime** [comment]
Thanks for pointing this out @PabloBotas.
We are in the process of building a new Monarch Website that should be launching to the public sometime this summer.
All our efforts are currently in the development of the new infrastructure and application so we won't be able to fix this issue before the new app launches.
Thanks again for the feedback and stay tuned for the new website.
