### ISSUE TITLE
Phenotype profile sufficiency score

### ISSUE THREAD

**Issue by oleraj** [monarch-initiative/helpdesk#68]
Hi Monarch team,

I am interested to use the Phenotype sufficiency score described in the PhenoDay presentation from 2014 for a project I'm working on.  I was wondering if this algorithm is available and/or if it has been updated to incorporate the latest diseases and phenotypes?  I don't see the tool available on the website.  Is this still a concept that is considered valid and useful for assessing how well a patient is phenotyped?  And is there a way to compute this through the REST API still?  I couldn't find any documentation about this.

Thanks!

Andrew

**Comment by sagehrke** [comment]
Hello @oleraj,

Thanks so much for reaching out to the Monarch team. We have received your message and are working on an answer to share with you soon. 

All the best,
Sarah
Project Manager, Monarch Initiative

**Comment by putmantime** [comment]
Hi Andrew,
Apologies for the delay.
This tool was built on legacy Monarch infrastructure and is indeed no longer part of our services in any form.
Raising this issue has made us discuss what a newer version of the sufficiency score tool would look like with our current services. 
Feel free to reach out to tim@tislab.org if you want to share more details about your use case.
