### ISSUE TITLE
Obtaining example phenopackets

### ISSUE THREAD

**Issue by LiNk-NY** [monarch-initiative/helpdesk#69]
Hi HelpDesk,

I am new to the project and I am working on an interface in the R language to import Phenopackets V2. 

Is it possible to obtain example phenopackets (v2) for examples and testing?

Thank you for your help in advance! :pray:  

Best regards,
Marcel

**Comment by sagehrke** [comment]
Hi Marcel -- Thanks for reaching out! 
@pnrobinson shared this response to send to you: 
here are some examples in YAML and JSON format -- http://phenopackets.org/phenopacket-tools/examples

Please let us know if you have any further questions. 

All the best,
Sarah

**Comment by LiNk-NY** [comment]
Hi Sarah, @sagehrke 

Thank you for your response!

The link you posted leads me to empty links, e.g., https://github.com/phenopackets/phenopacket-tools/tree/gh-pages/examples/phenopackets 

I was hoping for something similar to https://zenodo.org/record/3905420 which is great for testing V1 code in R. 

Thank you!

Best regards,
Marcel

**Comment by ielis** [comment]
Hi @LiNk-NY, 
after performing the fix as described in [the issue](https://github.com/phenopackets/phenopacket-tools/issues/153), the link to examples should work now. Thanks a lot for pointing this up and please let us know if you find any other issues.

All the best,
Daniel
