### ISSUE TITLE
question about MONDO:0009136

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/helpdesk#72]
See ticket from @ValWood 

I believe this is a Monarch question
https://github.com/monarch-initiative/mondo/issues/5794

**Comment by kevinschaper** [comment]
It looks like NOLA3 is a previous name for NOP10 (according to https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:14378), but when the monarch graph was built, OMIM hadn't picked that change up yet. It looks like OMIM is now showing it as a variant of NOP10, and we're just behind.
